spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:46580/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mXSKBorwyvPwhjVdrlziJphpprblnrMY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
